version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue_frontend
    ports:
      - "8080:80"
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge
