version: '3'
services:
  web:
    image: node:16
    container_name: vue_frontend
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: "npm run dev"
    networks:
      - frontend_network
networks:
  frontend_network:
    driver: bridge
