version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge
